version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    env_file: .flask.env
    expose:
      - 5000
    volumes: ['./flask:/app']
    depends_on:
      - postgres
      - redis

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8081:80"

  postgres:
    image: postgres
    container_name: postgres
    env_file: .postgres.env
    expose:
      - 5432
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data